//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Microsoft.AspNetCore.Identity
{
    internal class UI
    {
        internal class UIFrameworkAttribute : Attribute
        {
        }
    }
}