// <auto-generated />
using System;

namespace AngularSpa.Data.Migrations
{
    internal class MigrationAttribute : Attribute
    {
        private string v;

        public MigrationAttribute(string v)
        {
            this.v = v;
        }
    }
}